name: build repository

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo apt update -q
        sudo apt install -yq flatpak-builder
        flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
        git lfs pull

    - name: import signing key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: build packages
      run: find -name '*.appdata.xml' -execdir sh -c 'flatpak-builder --gpg-sign=DDACB75F4CC38E0B33FDAB43507CDE7678C283D4 --install-deps-from=flathub --repo=${{ github.workspace }}/repo --user build $(basename $PWD).yml' \;

    - name: copy static files
      run: install -Dt ${{ github.workspace }}/repo rsapak.flatpakrepo

    - name: deploy to github pages
      uses: crazy-max/ghaction-github-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        build_dir: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
